[tool.black]
line-length = 79
target-version = ['py312']
skip-string-normalization = true
extend-exclude = """
/(
|  migrations
|  venv
|  node_modules
)/
"""

[tool.ruff]
line-length = 79
indent-width = 4
target-version = "py312"

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true
# be careful with ruff's format as it
# ruins any nests without trailing commas

[tool.ruff.lint]
flake8-quotes.inline-quotes = "single"
flake8-tidy-imports.ban-relative-imports = "all"
select = ["E4", "E7", "E9", "F", "E501", "COM812", "Q000"]
exclude = ["*/migrations/*", "venv", "node_modules"]

[tool.isort]
profile = "google"
force_sort_within_sections = true
force_alphabetical_sort_within_sections = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY",
    "LOCALABSOLUTE", "LOCALFOLDER"]
no_lines_before = ["LOCALFOLDER"]
known_localabsolute = ["chattr"]
# the closest to google import order
# config I could make,  may be faulty

[tool.djlint]
profile = "django"
indent = 2
max_line_length = 79
max_blank_lines = 1
