# Generated by Django 5.0.4 on 2024-04-23 20:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'room_id',
                    models.CharField(db_index=True, verbose_name='ID'),
                ),
                (
                    'max_users',
                    models.IntegerField(
                        default=24, max_length=100, verbose_name='MaxUsers'
                    ),
                ),
                (
                    'max_time',
                    models.IntegerField(
                        default=1440, max_length=10080, verbose_name='MaxTime'
                    ),
                ),
            ],
        ),
    ]
