# Generated by Django 5.0.4 on 2024-04-24 20:31

from django.db import migrations
from django.db import models

import api.homepage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api_homepage', '0002_alter_room_max_time_alter_room_max_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='max_time',
        ),
        migrations.AddField(
            model_name='room',
            name='max_idle_time',
            field=models.IntegerField(
                default=1440,
                validators=[
                    api.homepage.validators.MaxIdleTimeValidator(10080)
                ],
                verbose_name='максимальное время бездействия комнаты',
            ),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_users',
            field=models.IntegerField(
                default=24,
                validators=[api.homepage.validators.MaxUsersValidator(100)],
                verbose_name='максимальное количество пользователей',
            ),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(
                db_index=True, verbose_name='идентификатор комнаты'
            ),
        ),
    ]
